In [1]:
import pandas as pd

df = pd.read_csv('v.csv')

In [2]:
for i in df.columns:
    if df[i].dtype == 'object':
        # Replace commas with dots in string columns
        df[i] = df[i].str.replace(',', '.')
        if df[i].str.contains('.').any():
            try:
                # Convert to float if possible
                df[i] = df[i].astype(float)
            except ValueError:
                # If conversion fails, keep as string
                pass

In [3]:
df

,Customer_ID,Edad,churn_estimado,retencion_estimado,CLTV_1_anio,CLTV_2_anios,CLTV_3_anios,CLTV_4_anios,CLTV_5_anios
0,6253,32,0.921767,0.078233,236.773154,254.159187,255.419822,255.512422,255.519201
1,68963,39,0.631783,0.368217,1529.650130,2058.308552,2238.726199,2301.102117,2322.593499
2,66967,36,0.409476,0.590524,985.568587,1531.833843,1830.813141,1996.585736,2088.185381
3,80423,67,0.627372,0.372628,27.901814,37.660394,41.030640,42.209794,42.620934
4,52471,44,0.623811,0.376189,170.051381,230.094730,251.029610,258.424132,261.027042
...,...,...,...,...,...,...,...,...,...
44048,62922,60,0.210150,0.789850,-3982.127160,-6934.277915,-9095.417172,-10698.149692,-11882.687127
44049,97887,46,0.476754,0.523246,4861.485979,7249.042619,8406.910860,8975.762058,9254.276459
44050,35639,74,0.598257,0.401743,4186.879882,5765.647518,6353.497815,6575.240522,6658.597391
44051,22903,42,0.613603,0.386397,3926.047164,5349.909081,5859.827911,6044.826451,6111.713956
44052,85889,48,0.528156,0.471844,1137.828678,1641.740642,1862.111050,1959.741649,2002.846693